package dev.brella.blasement.upnut.ingest

const val BLASEBALL_SORTING_NEWEST_FIRST = 0
const val BLASEBALL_SORTING_OLDEST_FIRST = 1
const val BLASEBALL_SORTING_TOP = 2
const val BLASEBALL_SORTING_HOT = 3

const val BLASEBALL_CATEGORY_PLAYS = 0
const val BLASEBALL_CATEGORY_CHANGES = 1
const val BLASEBALL_CATEGORY_SPECIAL = 2
const val BLASEBALL_CATEGORY_OUTCOMES = 3
const val BLASEBALL_CATEGORY_BOOK_FEED = 4